os:
  - linux

language: php

php:
  - '7.4'

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  
script:
  # - vendor/bin/phpunit
  # - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php,app/Http/Controllers/ProfileController.php,app/Http/Controllers/PostController.php,app/Http/Controllers
  # - npm run production
  # - jshint resources/assets/js/modules/*