os:
  - linux

language: php

php:
  - '7.4'

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 12.16
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  - cp .env.travis .env
  - php artisan key:generate
  
script:
  - vendor/bin/phpunit
  - phpcs --standard=PSR2 --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/js/*
